"use client"

import { useState } from "react"
import { Eye, EyeOff, LockKeyhole, Plus, ShieldCheck } from "lucide-react"
import { Navbar } from "@/components/navbar"
import { Button } from "@/components/ui/button"

export default function LoaderPage() {
  const [password, setPassword] = useState("")
  const [show, setShow] = useState(false)
  const [authorized, setAuthorized] = useState(false)
  const [error, setError] = useState("")
  const [scriptName, setScriptName] = useState("")
  async function enter() { const response = await fetch("/api/loader", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ password }) }); if (response.ok) { setAuthorized(true); setError("") } else setError("Incorrect loader password") }
  if (!authorized) return <div className="min-h-dvh"><Navbar /><main className="mx-auto flex min-h-[75vh] max-w-md items-center px-4"><div className="glass-panel w-full p-8 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-primary/15 text-primary"><LockKeyhole /></div><h1 className="mt-6 font-display text-3xl font-bold">Private loader</h1><p className="mt-2 text-sm leading-relaxed text-muted-foreground">This area is restricted to authorized maintainers.</p><div className="relative mt-7"><input autoFocus type={show ? "text" : "password"} value={password} onChange={(e) => setPassword(e.target.value)} onKeyDown={(e) => e.key === "Enter" && enter()} placeholder="Enter access password" className="h-12 w-full rounded-xl border border-border bg-background px-4 pr-12 outline-none focus:border-primary" /><button aria-label={show ? "Hide password" : "Show password"} onClick={() => setShow(!show)} className="absolute right-3 top-3 text-muted-foreground">{show ? <EyeOff size={18} /> : <Eye size={18} />}</button></div>{error && <p className="mt-3 text-sm text-destructive">{error}</p>}<Button className="mt-5 w-full" onClick={enter}>Enter loader</Button></div></main></div>
  return <div className="min-h-dvh"><Navbar /><main className="mx-auto max-w-6xl px-4 py-12"><div className="flex items-center justify-between"><div><div className="eyebrow"><ShieldCheck className="h-3.5 w-3.5" /> Authorized workspace</div><h1 className="mt-4 font-display text-4xl font-bold">Loader control room</h1></div><Button variant="outline" onClick={() => setAuthorized(false)}>Lock area</Button></div><div className="mt-10 grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><section className="glass-panel p-6"><h2 className="font-display text-xl font-semibold">Add script</h2><p className="mt-1 text-sm text-muted-foreground">Publish a Lua resource for your own projects.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><input value={scriptName} onChange={(e) => setScriptName(e.target.value)} placeholder="Script name" className="field" /><input placeholder="Game compatibility" className="field" /><input placeholder="Version" className="field" /><select className="field"><option>Free</option><option>Premium</option></select><textarea placeholder="Description" className="field min-h-28 sm:col-span-2" /><label className="flex cursor-pointer items-center justify-center rounded-xl border border-dashed border-border p-8 text-sm text-muted-foreground sm:col-span-2"><Plus className="mr-2 h-4 w-4" /> Upload .lua file<input type="file" accept=".lua" className="sr-only" /></label></div><Button className="mt-5">Publish {scriptName || "script"}</Button></section><section className="glass-panel p-6"><h2 className="font-display text-xl font-semibold">Management</h2><div className="mt-5 grid gap-3"><div className="stat-row"><span>Visible scripts</span><strong>3</strong></div><div className="stat-row"><span>Active keys</span><strong>128</strong></div><div className="stat-row"><span>Registered users</span><strong>842</strong></div></div><div className="mt-8 rounded-xl border border-primary/20 bg-primary/10 p-4 text-sm leading-relaxed text-muted-foreground">Use the database-backed API routes to add key management, user moderation, visibility toggles, and announcements.</div></section></div></main></div>
}
